In [2]:
import numpy as np


In [5]:
w  = np.random.randint(1,3,(10,64))
w

array([[2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1,
        1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1,
        2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2,
        1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1,
        1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2],
       [2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
        1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1,
        1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2],
       [1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1,
        2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
        2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2],
       [1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2,
        1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1,

In [14]:
arra = np.random.randint(1,3,(1200,64))
arra_v = arra.reshape(64,1200)
arra_v.shape

(64, 1200)

In [15]:
new = w.dot(arra_v)
new

array([[150, 148, 158, ..., 155, 156, 150],
       [146, 142, 149, ..., 146, 155, 146],
       [141, 141, 148, ..., 143, 150, 142],
       ...,
       [140, 141, 151, ..., 145, 154, 146],
       [147, 147, 155, ..., 149, 151, 144],
       [154, 156, 165, ..., 159, 163, 158]], shape=(10, 1200))

In [3]:
from sklearn.datasets import load_digits

digits = load_digits()
X = digits.data
y = digits.target
y

array([0, 1, 2, ..., 8, 9, 8], shape=(1797,))

In [19]:
from sklearn.model_selection import train_test_split
import numpy as np
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_train_rs = y_train.reshape(1,-1)
arr = np.random.randint(1,4,(3,3,3))
arr.size
y_train.max()

np.int64(9)

In [37]:
yy = np.zeros((y_train_rs.size,y_train.max()+1   ))
yy.shape

(1437, 10)

In [39]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])